# Generated by Django 6.0.1 on 2026-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
