# Generated by Django 6.0.1 on 2026-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profiles/default.jpeg', upload_to='profiles/'),
        ),
    ]
