# Generated by Django 6.0.1 on 2026-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
