# Generated by Django 6.0.1 on 2026-02-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_admin'),
        ('products', '0005_product_average_rating_product_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recently_viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_by', to='products.product'),
        ),
    ]
